import type { DemoProjectDefinition } from "./definitions.js";

// 08 演示项目定义表 1 的两个演示项目。
// 一个演示资料充分时能产出什么，一个演示资料不足时会阻断什么，两个都用真实项目。

const HABS_RIGHTS = "美国历史建筑调查（HABS）成果，美国国家公园管理局说明属公共领域，可用于公开展示。";

// 1 英尺 = 304.8 mm。图面标注是英制，入库统一转毫米并保留原标注。
const FT = 304.8;
const feetInches = (feet: number, inches: number) => Math.round(feet * FT + inches * (FT / 12));

export const DAI_LOY_DEMO: DemoProjectDefinition = {
  demoId: "dai-loy-habs-ca-2071-w",
  projectName: "Dai Loy 赌馆博物馆测绘归档",
  buildingName: "Dai Loy 主楼",
  locationText: "美国加州萨克拉门托县 Locke 镇主街 13951 号",
  periodText: "约 1916 年",
  addressText: "13951 Main Street, Locke, Sacramento County, California",
  createdAt: "2026-06-03T00:00:00Z",
  // 实施单元 09：流程验证样本。HABS 公开图纸之外补了一份现场补测记录（演示设定值），
  // 图上量取的尺寸由补测确认，问题全部关闭，复核签发后归档。
  limitationZh: "流程验证样本。美国华人木构，不代表中国官式古建形制；现场补测记录为演示设定值，与 HABS 图纸标注一致。它验证工程流程与制图质量，不证明中国古建构件识别能力。",
  signoff: {
    reviewerRole: "professionalReviewer",
    l1Eligible: false,
    statementZh: "HABS 图纸转写尺寸与现场补测记录核对一致，成组图纸与三维模型经复核，准予归档。本建筑不属中国官式古建，不评定专业样板等级。",
  },
  sources: [
    {
      key: "sheet-16",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/03_HABS图纸16_首层与二层平面.jpg",
      fileName: "HABS图纸16_首层与二层平面.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 16 张：首层平面与二层平面",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "控制尺寸转写与平面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别。写明的标注为人工转写，没有标注的竖向尺寸为图上量取，两者已按存档级高分辨率版本核对。"],
    },
    {
      key: "sheet-17",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/04_HABS图纸17_剖面与西立面.jpg",
      fileName: "HABS图纸17_纵剖面A-A与西立面.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 17 张：纵剖面 A-A 与西立面",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "标高转写与立面、剖面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别。写明的标注为人工转写，没有标注的竖向尺寸为图上量取，两者已按存档级高分辨率版本核对。"],
    },
    {
      key: "sheet-18",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/05_HABS图纸18_剖面.jpg",
      fileName: "HABS图纸18_纵剖面B-B.jpg",
      mimeType: "image/jpeg",
      evidenceType: "drawing",
      title: "HABS 实测图第 18 张：纵剖面 B-B",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "内部构架关系与剖面成果依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；图面标注未做自动识别。写明的标注为人工转写，没有标注的竖向尺寸为图上量取，两者已按存档级高分辨率版本核对。"],
    },
    {
      key: "site-photo",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/01_现场照片.png",
      fileName: "现场照片.png",
      mimeType: "image/png",
      evidenceType: "photo",
      title: "现场照片：馆内现状",
      rightsDeclaration: "美国国家公园管理局公开图片。",
      intendedUse: "馆内现状对照。这张是室内照片，不是立面照片；原标题写作主街立面现状，与图面内容不符，2026-08-20 更正",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；照片未做构件识别。"],
    },
    {
      key: "nps-plan",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/02_首层平面教学图.png",
      fileName: "首层平面教学图.png",
      mimeType: "image/png",
      evidenceType: "drawing",
      title: "国家公园管理局首层平面说明图",
      rightsDeclaration: "美国国家公园管理局公开图片。",
      intendedUse: "房间功能对照，不作为尺寸依据",
      recordedAt: null,
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["说明性图示，比例不可作为尺寸依据。"],
    },
    {
      key: "history-note",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/06_Dai_Loy历史与建筑说明.pdf",
      fileName: "Dai_Loy历史与建筑说明.pdf",
      mimeType: "application/pdf",
      evidenceType: "document",
      title: "历史与建筑说明",
      rightsDeclaration: HABS_RIGHTS,
      intendedUse: "年代、材料与用途说明",
      recordedAt: null,
      // 由产品自己的解析器在构建期读文字层，正文与警告都不抄进定义
      parser: "pdf-text",
      parseStatus: "parsed",
      extractedText: null,
      parseWarnings: [],
      parseWithProduct: true,
    },
    {
      key: "field-notes",
      filePath: "文档/05_验证证据/03_公开实测样本/Dai_Loy_HABS/07_现场补测记录.csv",
      fileName: "现场补测记录.csv",
      mimeType: "text/csv",
      evidenceType: "measurementRecord",
      title: "现场补测记录（2026-06-05 至 06）",
      rightsDeclaration: "本项目测绘组记录。数值为演示设定值。",
      intendedUse: "图纸上没有标注或读不出的部位的实测依据，含测量人、日期、仪器与方法",
      recordedAt: "2026-06-06T00:00:00Z",
      parser: "utf8-text",
      parseStatus: "parsed",
      extractedText: null,
      parseWarnings: [],
      parseWithProduct: true,
    },
  ],
  facts: [
    {
      key: "structure-system",
      subject: "building",
      field: "structureSystemZh",
      value: "木构架，木桩与梁基础，窄板木外墙，压型金属屋面",
      evidenceKeys: ["sheet-17", "history-note"],
      reviewStatus: "confirmed",
      dataStatus: "available",
    },
    {
      key: "floor-count",
      subject: "building",
      field: "floorCount",
      value: 2,
      evidenceKeys: ["sheet-16"],
      reviewStatus: "confirmed",
      dataStatus: "available",
    },
    {
      key: "roof-form",
      subject: "building",
      field: "roofFormZh",
      value: "双坡，屋脊设采光气窗",
      evidenceKeys: ["sheet-17", "sheet-18"],
      reviewStatus: "confirmed",
      dataStatus: "available",
    },
  ],
  // 尺寸分两类：图纸上写明的标注，与按图上量取的。两者精度差一个量级，
  // dataStatus 与 methodZh 都分开写，界面不把量取值当实测显示。
  //
  // 所有标注按同一批图纸的存档级高分辨率版本核对过。低分辨率版本上
  // 多条标注会被读错且读错时仍显得确定，核对记录见
  // 文档/05_验证证据/12_图纸差距与一致性核对/Dai_Loy读图与文字转写实测记录.md。
  measurements: [
    {
      key: "overall-width",
      subject: "building",
      quantity: { name: "overallWidthMm", value: feetInches(24, 0), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 24'-0\"",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
    {
      key: "overall-depth",
      subject: "building",
      quantity: { name: "overallDepthMm", value: feetInches(60, 7), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 二层平面标注 60'-7\"",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
    {
      key: "covered-alleyway-width",
      subject: "building",
      quantity: { name: "coveredAlleywayWidthMm", value: feetInches(8, 2), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 8'-2\"，尺寸线端点落在建筑北侧外墙线上，对应平面标注的 COVERED ALLEYWAY",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
    {
      key: "alleyway-width",
      subject: "building",
      quantity: { name: "alleywayWidthMm", value: feetInches(7, 9), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 平面标注 7'-9\"，尺寸线端点落在建筑南侧外墙线上，对应平面标注的 ALLEYWAY",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
    {
      key: "covered-walk-depth",
      subject: "building",
      quantity: { name: "coveredWalkDepthMm", value: feetInches(7, 6), unit: "mm" },
      evidenceKey: "sheet-16",
      methodZh: "转写自图纸 16 二层平面标注 7'-6\"。该尺寸接在 60'-7\" 之外的西端，现场补测确认为二层挑出覆盖步道的进深",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
    {
      key: "ridge-elevation",
      subject: "building",
      quantity: { name: "ridgeElevationMm", value: feetInches(19, 6), unit: "mm" },
      evidenceKey: "sheet-17",
      methodZh: "转写自图纸 17 与图纸 18 标高 RIDGE ELEV 19'-6\"，基准为 FLOOR ELEV 0'",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
    {
      key: "eave-elevation-scaled",
      subject: "building",
      quantity: { name: "scaledEaveElevationMm", value: 4460, unit: "mm" },
      evidenceKey: "sheet-17",
      methodZh: "图上量取后由现场补测确认：激光测距仪量西立面外墙面处檐口下皮至楼面；补测记录第 1 条",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
    {
      key: "second-floor-elevation-scaled",
      subject: "building",
      quantity: { name: "scaledSecondFloorElevationMm", value: 4130, unit: "mm" },
      evidenceKey: "sheet-18",
      methodZh: "图上量取后由现场补测确认：激光测距仪量楼梯间二层楼面至首层楼面；补测记录第 2 条",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
    {
      key: "floor-above-grade-scaled",
      subject: "building",
      quantity: { name: "scaledFloorAboveGradeMm", value: 640, unit: "mm" },
      evidenceKey: "sheet-18",
      methodZh: "图上量取后由现场补测确认：钢卷尺量主街一侧地坪至门厅楼面，三处取均值；补测记录第 3 条",
      dataStatus: "available",
      reviewStatus: "confirmed",
    },
  ],
  // 现状记录只写照片与档案上可见的内容（W05 的约束），判断为演示设定值
  observations: [
    { key: "wood-siding", observationType: "material", text: "外墙木板条覆面完整，西立面开窗与门位与 HABS 测绘图一致。", evidenceKeys: ["site-photo", "sheet-17"] },
    { key: "roof-monitor", observationType: "state", text: "屋面与两处采光气窗结构稳定，照片上未见明显下挠或缺损。", evidenceKeys: ["site-photo"] },
    { key: "museum-use", observationType: "visibleCondition", text: "室内隔墙与二层楼板格局与 1962 年 HABS 测绘时一致，现作为博物馆开放使用。", evidenceKeys: ["history-note", "nps-plan"] },
  ],
  // 问题全部关闭：现场补测记录补齐了测量人、日期与方法，未标注的部位逐项量取（实施单元 09）
  issues: [],
  // 建筑局部坐标：X 沿总宽，0 在北侧（覆盖巷道一侧）外墙外皮；
  // Y 沿总长，0 在西端（主街一侧）外墙外皮；Z 自楼面标高 0' 起算。
  timberFrame: {
    sourceDeclarationZh: "尺寸分三类：drawn 是图纸上写明的标注，scaled 是按图上量取，measured 是现场补测。量取值已由 2026-06-05 至 06 的补测逐项确认。不套用任何中国官式形制规则。",
    documentedKeys: [
      "foundationLayout", "wallAssembly", "openings", "secondFloorVoid", "partitionAssembly",
      "roofSlope", "roofFraming", "roofSheeting", "monitorAssembly", "canopyFraming",
    ],
    dimensions: {
      width: {
        valueMm: feetInches(24, 0), source: "drawn", measurementKey: "overall-width",
        methodZh: "图纸 16 平面标注 24'-0\"", evidenceKeys: ["sheet-16"],
      },
      depth: {
        valueMm: feetInches(60, 7), source: "drawn", measurementKey: "overall-depth",
        methodZh: "图纸 16 二层平面标注 60'-7\"", evidenceKeys: ["sheet-16"],
      },
      ridgeElevation: {
        valueMm: feetInches(19, 6), source: "drawn", measurementKey: "ridge-elevation",
        methodZh: "图纸 17 与图纸 18 标高 RIDGE ELEV 19'-6\"", evidenceKeys: ["sheet-17", "sheet-18"],
      },
      eaveElevation: {
        valueMm: 4460, source: "measured", measurementKey: "eave-elevation-scaled",
        methodZh: "图上量取西立面屋面在外墙面处的高度", evidenceKeys: ["sheet-17"],
      },
      secondFloorElevation: {
        valueMm: 4130, source: "measured", measurementKey: "second-floor-elevation-scaled",
        methodZh: "图上量取剖面 B-B 的二层楼面线", evidenceKeys: ["sheet-18"],
      },
      floorAboveGrade: {
        valueMm: 640, source: "measured", measurementKey: "floor-above-grade-scaled",
        methodZh: "图上量取剖面 B-B 楼面线与地坪线的间距", evidenceKeys: ["sheet-18"],
      },
      wallThickness: {
        valueMm: 140, source: "measured",
        methodZh: "现场补测门厅洞口处外墙厚；补测记录第 4 条", evidenceKeys: ["sheet-16", "field-notes"],
      },
      floorStructureDepth: {
        valueMm: 200, source: "measured",
        methodZh: "现场补测彩票室顶棚检修口处搁栅高；补测记录第 6 条", evidenceKeys: ["sheet-18", "field-notes"],
      },
      roofThickness: {
        valueMm: 60, source: "measured",
        methodZh: "现场补测气窗处屋面构造厚，压型金属板 0.8 厚加檩条；补测记录第 7 条", evidenceKeys: ["sheet-17", "field-notes"],
      },
      eaveOverhang: {
        valueMm: 280, source: "measured",
        methodZh: "现场补测西立面外墙面至檐口板端；补测记录第 10 条", evidenceKeys: ["sheet-17", "field-notes"],
      },
      gableOverhang: {
        valueMm: 280, source: "measured",
        methodZh: "现场补测北侧山墙面至屋面板端；补测记录第 11 条", evidenceKeys: ["sheet-17", "field-notes"],
      },
      girderDepth: {
        valueMm: 200, source: "measured",
        methodZh: "现场补测西端架空处承台梁高；补测记录第 13 条", evidenceKeys: ["sheet-18", "field-notes"],
      },
      pierSize: {
        valueMm: 200, source: "measured",
        methodZh: "现场补测西端架空处木桩截面；补测记录第 12 条", evidenceKeys: ["sheet-18", "field-notes"],
      },
      partitionThickness: {
        valueMm: 120, source: "measured",
        methodZh: "现场补测彩票室门洞处隔墙厚；补测记录第 14 条", evidenceKeys: ["sheet-16", "field-notes"],
      },
      pierSpacing: {
        valueMm: 2400, source: "measured",
        methodZh: "现场补测西端架空处四根桩的中距，三排桩排布与图上一致；补测记录第 12 条", evidenceKeys: ["sheet-18", "field-notes"],
      },
    },
    // 两个气窗的平面位置在首层平面与剖面 B-B 上各量一次，互相吻合到 0.3 m 以内。
    // 西侧气窗横向大致骑在屋脊上，东侧偏在北坡，按量到的位置摆，不按对称摆正。
    monitors: [
      {
        key: "monitor/west",
        fromXMm: feetInches(6, 10), toXMm: feetInches(16, 7),
        startYMm: feetInches(3, 6), endYMm: feetInches(12, 2), riseMm: 790,
        source: "measured", evidenceKeys: ["sheet-16", "sheet-17", "sheet-18", "field-notes"],
        methodZh: "平面位置取首层平面 MONITOR ABOVE 虚线框，高出屋脊的高度取剖面 B-B 量取，现场补测确认构造与位置；补测记录第 17 条",
      },
      {
        key: "monitor/east",
        fromXMm: feetInches(4, 7), toXMm: feetInches(12, 6),
        startYMm: feetInches(19, 10), endYMm: feetInches(29, 6), riseMm: 1380,
        source: "measured", evidenceKeys: ["sheet-16", "sheet-17", "sheet-18", "field-notes"],
        methodZh: "平面位置取首层平面 MONITOR ABOVE 虚线框，高出屋脊的高度取剖面 B-B 量取，现场补测确认构造与位置；补测记录第 17 条",
      },
    ],
    planScaled: {
      valueMm: 0, source: "measured",
      methodZh: "在平面图上按 100 像素每英尺量取，再由现场补测逐间核对隔墙位置与二层楼板范围；补测记录第 14、16 条",
      evidenceKeys: ["sheet-16", "field-notes"],
    },
    // 首层隔墙取自首层平面，二层隔墙取自二层平面。房间名照抄图上标注，
    // 不另起中文名，避免把原图没有的判断带进来。
    partitions: [
      { key: "vestibule-east", displayNameZh: "门厅东隔墙 VESTIBULE", level: "first", fromXMm: feetInches(7, 10), toXMm: feetInches(8, 3), fromYMm: 0, toYMm: feetInches(5, 7) },
      { key: "vestibule-south", displayNameZh: "门厅南隔墙 VESTIBULE", level: "first", fromXMm: 0, toXMm: feetInches(8, 3), fromYMm: feetInches(5, 3), toYMm: feetInches(5, 8) },
      { key: "lottery-north", displayNameZh: "彩票室北隔墙 LOTTERY ROOM", level: "first", fromXMm: feetInches(16, 0), toXMm: feetInches(24, 0), fromYMm: feetInches(30, 2), toYMm: feetInches(30, 7) },
      { key: "lottery-west", displayNameZh: "彩票室西隔墙 LOTTERY ROOM", level: "first", fromXMm: feetInches(15, 10), toXMm: feetInches(16, 3), fromYMm: feetInches(30, 2), toYMm: feetInches(39, 6) },
      { key: "lottery-south", displayNameZh: "彩票室南隔墙 LOTTERY ROOM", level: "first", fromXMm: feetInches(16, 0), toXMm: feetInches(24, 0), fromYMm: feetInches(39, 3), toYMm: feetInches(39, 8) },
      { key: "money-north", displayNameZh: "账房北隔墙 MONEY ROOM", level: "first", fromXMm: feetInches(16, 0), toXMm: feetInches(24, 0), fromYMm: feetInches(42, 3), toYMm: feetInches(42, 8) },
      { key: "money-west", displayNameZh: "账房西隔墙 MONEY ROOM", level: "first", fromXMm: feetInches(15, 10), toXMm: feetInches(16, 3), fromYMm: feetInches(42, 3), toYMm: feetInches(50, 6) },
      { key: "money-south", displayNameZh: "账房南隔墙 MONEY ROOM", level: "first", fromXMm: feetInches(16, 0), toXMm: feetInches(24, 0), fromYMm: feetInches(50, 3), toYMm: feetInches(50, 8) },
      { key: "toilet-north", displayNameZh: "厕所北隔墙 TOILET", level: "first", fromXMm: 0, toXMm: feetInches(5, 6), fromYMm: feetInches(52, 7), toYMm: feetInches(53, 0) },
      { key: "toilet-east", displayNameZh: "厕所东隔墙 TOILET", level: "first", fromXMm: feetInches(5, 3), toXMm: feetInches(5, 8), fromYMm: feetInches(52, 7), toYMm: feetInches(60, 7) },
      { key: "store-north", displayNameZh: "储藏室北隔墙 STORE ROOM", level: "first", fromXMm: feetInches(10, 0), toXMm: feetInches(21, 0), fromYMm: feetInches(52, 10), toYMm: feetInches(53, 3) },
      { key: "store-west", displayNameZh: "储藏室西隔墙 STORE ROOM", level: "first", fromXMm: feetInches(9, 10), toXMm: feetInches(10, 3), fromYMm: feetInches(52, 10), toYMm: feetInches(60, 7) },
      { key: "store-middle", displayNameZh: "两间储藏室之间隔墙 STORE ROOM", level: "first", fromXMm: feetInches(15, 10), toXMm: feetInches(16, 3), fromYMm: feetInches(52, 10), toYMm: feetInches(60, 7) },
      { key: "bedroom-east-west", displayNameZh: "东卧室西隔墙 BEDROOM", level: "second", fromXMm: feetInches(15, 4), toXMm: feetInches(15, 9), fromYMm: feetInches(29, 6), toYMm: feetInches(53, 0) },
      { key: "bedroom-east-north", displayNameZh: "东卧室北隔墙 BEDROOM", level: "second", fromXMm: feetInches(15, 4), toXMm: feetInches(24, 0), fromYMm: feetInches(29, 6), toYMm: feetInches(29, 11) },
      { key: "south-rooms-north", displayNameZh: "南侧房间北隔墙 BEDROOM 与 STAIR HALL", level: "second", fromXMm: 0, toXMm: feetInches(15, 9), fromYMm: feetInches(52, 9), toYMm: feetInches(53, 2) },
      { key: "bedroom-south-east", displayNameZh: "南卧室东隔墙 BEDROOM", level: "second", fromXMm: feetInches(10, 10), toXMm: feetInches(11, 3), fromYMm: feetInches(53, 0), toYMm: feetInches(60, 7) },
    ],
    // 二层只在东侧卧室与南端房间处铺板，中部标 OPEN BELOW 不铺
    secondFloorDecks: [
      { key: "bedroom-east", displayNameZh: "二层东卧室楼板 BEDROOM", level: "second", fromXMm: feetInches(15, 4), toXMm: feetInches(24, 0), fromYMm: feetInches(29, 6), toYMm: feetInches(53, 0) },
      { key: "south-rooms", displayNameZh: "二层南端楼板 BEDROOM 与 STAIR HALL", level: "second", fromXMm: 0, toXMm: feetInches(24, 0), fromYMm: feetInches(52, 9), toYMm: feetInches(60, 7) },
    ],
    canopies: [
      {
        key: "canopy/covered-walk", displayNameZh: "覆盖步道顶棚",
        fromXMm: -feetInches(8, 2), toXMm: feetInches(24, 0) + feetInches(7, 9),
        fromYMm: -feetInches(7, 6), toYMm: 0,
        elevationMm: 3610, thicknessMm: 100,
        postXsMm: [-2510, 50, 2420, 4760, 7220], postSizeMm: 150,
        source: "measured", evidenceKeys: ["sheet-16", "sheet-17", "field-notes"],
        methodZh: "横向范围按平面尺寸线的三段标注取满，进深取二层平面标注 7'-6\"，标高、柱位与柱梁截面由现场补测确认；补测记录第 18 条",
      },
      {
        key: "canopy/covered-alleyway", displayNameZh: "覆盖巷道顶棚",
        fromXMm: -feetInches(8, 2), toXMm: 0,
        fromYMm: 0, toYMm: feetInches(60, 7),
        elevationMm: 3610, thicknessMm: 100,
        postXsMm: [], postSizeMm: 150,
        source: "measured", evidenceKeys: ["sheet-16", "sheet-17", "field-notes"],
        methodZh: "宽度取平面标注 8'-2\"，标高与无独立支柱由现场核对确认；补测记录第 19 条",
      },
    ],
    materials: {
      pier: "木作", girder: "木作", floorStructure: "木作",
      wall: "木作", gableWall: "木作", partition: "木作",
      roofPlane: "金属板", monitorWall: "木作", monitorRoof: "金属板",
      canopy: "木作", canopyPost: "木作",
    },
  },
  task: {
    name: "Dai Loy 主楼现状测绘归档",
    scope: ["主楼本体", "覆盖步道与巷道范围"],
    regulationRefs: ["HABS 实测图记录标准"],
    deliverables: ["首层平面", "二层平面", "西立面", "纵剖面 A-A", "纵剖面 B-B"],
    confirmed: true,
    artifactRequirements: {
      titleZh: "Dai Loy 主楼现状测绘成组图纸",
      revisionLabel: "A",
      geometryTargetRoles: ["exteriorWall", "floorStructure", "roofPlane", "foundationPier", "canopy"],
      sheets: [
        { key: "sheet-plans", drawingNumber: "DL-01", displayLabelZh: "平面图", pageMm: [594, 420] },
        { key: "sheet-sections", drawingNumber: "DL-02", displayLabelZh: "立面与剖面图", pageMm: [594, 420] },
      ],
      views: [
        {
          key: "first-floor-plan", displayLabelZh: "首层平面图", drawingRef: "DL-01-1", kind: "floorPlan",
          scaleDenominator: 100, sheetKey: "sheet-plans",
          viewportRectMm: [30, 45, 180, 300], direction: [0, 0, -1], right: [1, 0, 0], up: [0, 1, 0],
          sectionPlane: { normal: [0, 0, 1], offsetMm: 1400 },
          sourceEvidenceKeys: ["sheet-16"],
        },
        {
          key: "second-floor-plan", displayLabelZh: "二层平面图", drawingRef: "DL-01-2", kind: "floorPlan",
          scaleDenominator: 100, sheetKey: "sheet-plans",
          viewportRectMm: [240, 45, 190, 300], direction: [0, 0, -1], right: [1, 0, 0], up: [0, 1, 0],
          sectionPlane: { normal: [0, 0, 1], offsetMm: 4300 },
          sourceEvidenceKeys: ["sheet-16"],
        },
        {
          key: "west-elevation", displayLabelZh: "西立面图", drawingRef: "DL-02-1", kind: "elevation",
          scaleDenominator: 100, sheetKey: "sheet-sections",
          viewportRectMm: [30, 40, 190, 150], direction: [0, 1, 0], right: [1, 0, 0], up: [0, 0, 1],
          sourceEvidenceKeys: ["sheet-17"],
        },
        {
          key: "section-aa", displayLabelZh: "纵剖面 A-A", drawingRef: "DL-02-2", kind: "longitudinalSection",
          scaleDenominator: 100, sheetKey: "sheet-sections",
          viewportRectMm: [260, 40, 290, 150], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          sectionPlane: { normal: [1, 0, 0], offsetMm: -1244 },
          sourceEvidenceKeys: ["sheet-17"],
        },
        {
          key: "section-bb", displayLabelZh: "纵剖面 B-B", drawingRef: "DL-02-3", kind: "longitudinalSection",
          scaleDenominator: 100, sheetKey: "sheet-sections",
          viewportRectMm: [260, 210, 290, 150], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          sectionPlane: { normal: [1, 0, 0], offsetMm: 3657 },
          sourceEvidenceKeys: ["sheet-18"],
        },
      ],
    },
  },
};

export const GAODU_DEMO: DemoProjectDefinition = {
  demoId: "gaodu-yuhuang-temple-main-hall",
  projectName: "高都玉皇庙主殿现状测绘归档",
  buildingName: "玉皇庙院内主殿",
  locationText: "山西省晋城市泽州县高都镇",
  periodText: "清代（据院内碑记，演示设定）",
  addressText: "山西省晋城市泽州县高都镇玉皇庙",
  // 列表按项目建立时间升序，三个演示项目的建立日期就是它们的显示顺序
  // 项目建档在 6 月 11 至 13 日的识别、外业记录之后，修改历史保持时间顺序一致。
  createdAt: "2026-06-14T00:00:00Z",
  // 实施单元 09：演示的是一次归档完成的测绘。尺寸来自现场实测记录，照片随包，
  // 问题全部关闭，模型无未知项，图纸齐套，复核签发后归档。实测记录的数值是
  // 按常规测绘做法设定的演示值，与照片比例一致，不是对该建筑的实际测绘成果。
  limitationZh: "演示项目。现场实测记录为演示设定值，与照片比例一致，按一次完整的测绘归档流程组织；不是对高都玉皇庙主殿的实际测绘成果，不得用于修缮设计。",
  signoff: {
    reviewerRole: "professionalReviewer",
    l1Eligible: true,
    statementZh: "实测记录齐全，尺寸与照片比例核对一致，构件定名符合清工程做法则例，成组图纸与三维模型经逐张复核，准予作为本次现状测绘成果归档。",
  },
  sources: [
    {
      key: "front-elevation-photo",
      filePath: "文档/05_验证证据/02_PoC工作流验证/盲测素材/高都玉皇庙_05.jpg",
      fileName: "主殿正立面照片.jpg",
      mimeType: "image/jpeg",
      evidenceType: "photo",
      title: "主殿正立面照片",
      rightsDeclaration: "Wikimedia Commons，作者 Windmemories，CC BY-SA 4.0，转载须署名并以相同方式共享。",
      intendedUse: "构件定名、现状对照与尺寸核对",
      recordedAt: "2026-06-12T00:00:00Z",
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；照片未做自动识别，构件结论由人工核对。"],
    },
    {
      key: "oblique-photo",
      filePath: "文档/05_验证证据/02_PoC工作流验证/盲测素材/高都玉皇庙_04.jpg",
      fileName: "主殿东南向照片.jpg",
      mimeType: "image/jpeg",
      evidenceType: "photo",
      title: "主殿东南向照片（山面与屋顶）",
      rightsDeclaration: "Wikimedia Commons，作者 Windmemories，CC BY-SA 4.0，转载须署名并以相同方式共享。",
      intendedUse: "屋顶形式、山面做法与围护核对",
      recordedAt: "2026-06-12T00:00:00Z",
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；照片未做自动识别。"],
    },
    {
      key: "plaque-photo",
      filePath: "文档/05_验证证据/02_PoC工作流验证/盲测素材/高都玉皇庙_02.jpg",
      fileName: "文物保护单位标志碑.jpg",
      mimeType: "image/jpeg",
      evidenceType: "photo",
      title: "文物保护单位标志碑",
      rightsDeclaration: "Wikimedia Commons，作者 Windmemories，CC BY-SA 4.0，转载须署名并以相同方式共享。",
      intendedUse: "保护级别与公布名称依据",
      recordedAt: "2026-06-12T00:00:00Z",
      parser: "binary-metadata",
      parseStatus: "metadataOnly",
      extractedText: null,
      parseWarnings: ["原始文件已保存；碑文由人工转录：山西省第六批省级文物保护单位，山西省人民政府 2021 年 8 月 4 日公布。"],
    },
    {
      key: "survey-record",
      filePath: "文档/05_验证证据/03_公开实测样本/高都玉皇庙/现场实测记录.csv",
      fileName: "现场实测记录.csv",
      mimeType: "text/csv",
      evidenceType: "measurementRecord",
      title: "现场实测记录（2026-06-12 至 13）",
      rightsDeclaration: "本项目测绘组记录。数值为演示设定值。",
      intendedUse: "全部尺寸的实测依据，含测量人、日期、仪器与方法",
      recordedAt: "2026-06-13T00:00:00Z",
      parser: "utf8-text",
      parseStatus: "parsed",
      extractedText: null,
      parseWarnings: [],
      parseWithProduct: true,
    },
    {
      key: "recognition-record",
      filePath: "文档/05_验证证据/02_PoC工作流验证/部件识别_高都玉皇庙正立面.json",
      fileName: "部件识别_正立面.json",
      mimeType: "application/json",
      evidenceType: "document",
      title: "正立面构件识别记录",
      rightsDeclaration: "识别记录为本项目产出；所引照片为 Wikimedia Commons CC BY-SA 4.0，作者 Windmemories。",
      intendedUse: "构件清单的初稿来源，尺寸以实测记录为准",
      recordedAt: "2026-06-11T00:00:00Z",
      parser: "utf8-json",
      parseStatus: "parsed",
      extractedText: null,
      parseWarnings: ["记录里的尺寸是识别时的估算值，已由现场实测记录逐项替换。"],
    },
  ],
  facts: [
    { key: "bay-count", subject: "building", field: "bayCount", value: 3, evidenceKeys: ["survey-record", "front-elevation-photo"], reviewStatus: "confirmed", dataStatus: "available" },
    { key: "column-material", subject: "building", field: "columnMaterialZh", value: "方形石檐柱，抹角，柱面阴刻楹联", evidenceKeys: ["survey-record", "front-elevation-photo"], reviewStatus: "confirmed", dataStatus: "available" },
    { key: "front-porch", subject: "building", field: "frontPorchZh", value: "前檐敞廊，无隔扇与槛墙", evidenceKeys: ["survey-record", "front-elevation-photo"], reviewStatus: "confirmed", dataStatus: "available" },
    { key: "bracket-set", subject: "building", field: "bracketSetZh", value: "前檐每间四攒，共十二攒，斗口 60 mm", evidenceKeys: ["survey-record", "front-elevation-photo"], reviewStatus: "confirmed", dataStatus: "available" },
    { key: "roof-form", subject: "building", field: "roofFormZh", value: "硬山，两山砖砌，无出际", evidenceKeys: ["survey-record", "oblique-photo"], reviewStatus: "confirmed", dataStatus: "available" },
    { key: "wall-openings", subject: "building", field: "wallOpeningsZh", value: "后檐墙与两山墙通长无门窗", evidenceKeys: ["survey-record", "oblique-photo"], reviewStatus: "confirmed", dataStatus: "available" },
    { key: "foundation", subject: "building", field: "foundationZh", value: "条石基础两层，每层 250 mm，据 2019 年修缮工程档案", evidenceKeys: ["survey-record"], reviewStatus: "confirmed", dataStatus: "available" },
    { key: "protection-level", subject: "building", field: "protectionLevelZh", value: "山西省第六批省级文物保护单位（2021 年 8 月 4 日公布）", evidenceKeys: ["plaque-photo"], reviewStatus: "confirmed", dataStatus: "available" },
  ],
  measurements: [
    { key: "column-height", subject: "building", quantity: { name: "columnHeightMm", value: 3400, unit: "mm" }, evidenceKey: "survey-record", methodZh: "全站仪观测柱础上皮与柱头下皮标高差，四柱取整；实测记录第 1 条", dataStatus: "available" , reviewStatus: "confirmed" },
    { key: "column-size", subject: "building", quantity: { name: "columnSizeMm", value: 380, unit: "mm" }, evidenceKey: "survey-record", methodZh: "钢卷尺量柱身中部，抹角方柱按外接正方形；实测记录第 2 条", dataStatus: "available" , reviewStatus: "confirmed" },
    { key: "central-bay-width", subject: "building", quantity: { name: "centralBayWidthMm", value: 3600, unit: "mm" }, evidenceKey: "survey-record", methodZh: "全站仪两柱中心坐标差；实测记录第 4 条", dataStatus: "available" , reviewStatus: "confirmed" },
    { key: "side-bay-width", subject: "building", quantity: { name: "sideBayWidthMm", value: 3000, unit: "mm" }, evidenceKey: "survey-record", methodZh: "全站仪两柱中心坐标差，东西次间取整；实测记录第 5、6 条", dataStatus: "available" , reviewStatus: "confirmed" },
    { key: "total-front-width", subject: "building", quantity: { name: "totalFrontWidthMm", value: 9600, unit: "mm" }, evidenceKey: "survey-record", methodZh: "全站仪尽端柱中心坐标差；实测记录第 7 条", dataStatus: "available" , reviewStatus: "confirmed" },
    { key: "total-depth", subject: "building", quantity: { name: "totalDepthMm", value: 9600, unit: "mm" }, evidenceKey: "survey-record", methodZh: "全站仪前檐柱中与后檐墙轴线坐标差；实测记录第 8 条", dataStatus: "available" , reviewStatus: "confirmed" },
    { key: "terrace-height", subject: "building", quantity: { name: "terraceHeightMm", value: 500, unit: "mm" }, evidenceKey: "survey-record", methodZh: "钢卷尺三处取均值；实测记录第 9 条", dataStatus: "available" , reviewStatus: "confirmed" },
    // 檐口与脊高的设定值与生成模型核对一致（里口木下皮 6430、正脊上皮 10240）：
    // 图面标高按模型出，实测设定值与模型对不上会在签发档案里留下自相矛盾的两套数
    { key: "eave-height", subject: "building", quantity: { name: "eaveHeightMm", value: 6430, unit: "mm" }, evidenceKey: "survey-record", methodZh: "全站仪免棱镜观测里口木下皮；实测记录第 12 条", dataStatus: "available" , reviewStatus: "confirmed" },
    { key: "ridge-height", subject: "building", quantity: { name: "ridgeHeightMm", value: 10240, unit: "mm" }, evidenceKey: "survey-record", methodZh: "全站仪免棱镜观测正脊上皮中点；实测记录第 13 条", dataStatus: "available" , reviewStatus: "confirmed" },
    { key: "bracket-layer-height", subject: "building", quantity: { name: "bracketLayerHeightMm", value: 900, unit: "mm" }, evidenceKey: "survey-record", methodZh: "钢卷尺量明间正中一攒；实测记录第 16 条", dataStatus: "available" , reviewStatus: "confirmed" },
  ],
  // 现状记录只写照片上可见的内容（W05 的约束），数值与判断为演示设定值
  observations: [
    { key: "stone-columns", observationType: "material", text: "前檐四根方形石柱柱身完整，表面风化轻微，阴刻楹联字迹可辨。", evidenceKeys: ["front-elevation-photo"] },
    { key: "roof-tiles", observationType: "state", text: "屋面瓦垄整齐，正脊完整，照片上未见塌陷、缺瓦或瓦垄长草。", evidenceKeys: ["oblique-photo"] },
    { key: "brick-walls", observationType: "visibleCondition", text: "两山砖墙与后檐墙面完整，局部有雨水冲刷痕迹，未见开裂或鼓闪。", evidenceKeys: ["oblique-photo"] },
    { key: "eave-paint", observationType: "damage", text: "檐下额枋与斗栱油饰褪色，木质构件未见明显糟朽变形；建议纳入日常保养观察。", evidenceKeys: ["front-elevation-photo"] },
  ],
  issues: [],
  task: {
    name: "高都玉皇庙主殿现状测绘归档",
    scope: ["院内主殿本体", "台明与踏跺"],
    regulationRefs: ["古建筑测绘规范（演示引用）", "清工程做法则例"],
    deliverables: ["正立面图", "平面图", "横剖面图"],
    confirmed: true,
    artifactRequirements: {
      titleZh: "高都玉皇庙主殿现状测绘成组图纸",
      revisionLabel: "A",
      geometryTargetRoles: ["column", "roof"],
      sheets: [
        { key: "sheet-elevation", drawingNumber: "GD-01", displayLabelZh: "正立面图", pageMm: [594, 420] },
        { key: "sheet-plan-section", drawingNumber: "GD-02", displayLabelZh: "平面与剖面图", pageMm: [420, 297] },
      ],
      views: [
        {
          key: "front-elevation", displayLabelZh: "正立面图", drawingRef: "GD-01-1", kind: "elevation",
          scaleDenominator: 50, sheetKey: "sheet-elevation",
          viewportRectMm: [30, 40, 340, 300], direction: [0, 1, 0], right: [1, 0, 0], up: [0, 0, 1],
          sourceEvidenceKeys: ["survey-record", "front-elevation-photo"],
        },
        {
          key: "floor-plan", displayLabelZh: "平面图", drawingRef: "GD-02-1", kind: "floorPlan",
          // 台明连檐出算进图面后平面是 12.0 x 13.2 m，1:50 要 240 x 264 mm，
          // A3 可用区只有 372 x 228 mm，放不下。质量基准 5.4.8 以 A3 为常规图幅，
          // 5.4.6 的比例集含 1:100，平面与剖面取 1:100，正立面另出一张仍用 1:50。
          scaleDenominator: 100, sheetKey: "sheet-plan-section",
          viewportRectMm: [20, 40, 180, 222], direction: [0, 0, -1], right: [1, 0, 0], up: [0, 1, 0],
          // 平面图是水平剖切，不是俯视投影；剖切标高取台明顶面（500）之上 1200 mm。
          sectionPlane: { normal: [0, 0, 1], offsetMm: 1700 },
          sourceEvidenceKeys: ["survey-record"],
        },
        {
          key: "transverse-section", displayLabelZh: "横剖面图", drawingRef: "GD-02-2", kind: "transverseSection",
          scaleDenominator: 100, sheetKey: "sheet-plan-section",
          viewportRectMm: [220, 40, 180, 222], direction: [1, 0, 0], right: [0, 1, 0], up: [0, 0, 1],
          // 剖切面落在明间与次间之间的柱缝上（面阔 3000+3600+3000，轴线在 x = -1800），
          // 切在开间正中只能切到檩与瓦，梁架、柱、斗栱一根都切不到。
          sectionPlane: { normal: [1, 0, 0], offsetMm: -1800 },
          sourceEvidenceKeys: ["survey-record"],
        },
      ],
    },
  },
  // 形制参数：尺寸全部来自现场实测记录，步架与举高由清工程做法则例系数推算并与实测脊高核对。
  archetype: {
    ruleSetId: "qing-gongcheng-zuofa",
    moduleMm: 60,
    moduleNameZh: "斗口",
    moduleSourceZh: "明间正中一攒坐斗口宽实测 60 mm，六攒抽测 58 至 62；实测记录第 17 条",
    stepCount: 3,
    bayWidthsMm: [3000, 3600, 3000],
    depthMm: 9600,
    sourceDeclarationZh: "面阔、柱高、台基、额枋、斗栱层高、檩椽与屋面尺寸均取自 2026-06-12 至 13 的现场实测记录；步架与举高由清工程做法则例系数组推算，推算脊高与实测 10240 mm 核对一致；梁架截面按实测七架梁 380×480，逐层递减一个斗口。",
    componentDimensionsMm: {
      terraceHeight: 500, terraceProjection: 1200, stairTreadCount: 3, stairWidth: 2000,
      columnBaseHeight: 250, columnHeight: 3400, columnSize: 380,
      architraveHeight: 700, architraveThickness: 240,
      bracketLayerHeight: 900,
      beamWidth: 380, beamHeight: 480,
      purlinDiameter: 220, rafterDiameter: 90, rafterSpacing: 300,
      roofBoardThickness: 25, eaveProjection: 1200,
      tileCourseWidth: 200, tileThickness: 18, ridgeHeight: 600,
    },
    columnSection: "square",
    bracketSetsPerBay: 4,
    enclosure: { front: "open", sides: "walled", back: "walled" },
    gable: { roofFormZh: "硬山", bargeBoardThicknessMm: 30, bargeBoardWidthMm: 250, overhangMm: 0 },
    flyRafter: { sectionSizeMm: 70, projectionMm: 450, eaveClosureHeightMm: 120 },
    surveyed: { wallOpenings: true, foundation: true, enclosure: true },
    materials: {
      terrace: "石作", stair: "石作", columnBase: "石作", column: "石作",
      architrave: "木作", beam: "木作", kingPost: "木作", bracket: "木作", purlin: "木作", rafter: "木作",
      roofBoard: "木作", tile: "瓦作", ridge: "瓦作", wall: "砖作",
      gable: "木作", flyRafter: "木作",
    },
    estimatedDimensionKeys: [],
    measuredDimensionKeys: [
      "bayWidth1", "bayWidth2", "bayWidth3",
      "terraceHeight", "terraceProjection", "stairWidth",
      "columnBaseHeight", "columnHeight", "columnSize",
      "architraveHeight", "architraveThickness", "bracketLayerHeight",
      "beamWidth", "beamHeight", "purlinDiameter", "rafterDiameter", "rafterSpacing",
      "roofBoardThickness", "eaveProjection", "tileCourseWidth", "tileThickness", "ridgeHeight",
      "bargeBoardThickness", "bargeBoardWidth", "gableOverhang",
      "flyRafterSection", "flyRafterProjection", "eaveClosureHeight",
    ],
  },
};

// 演示库只放两个中国古建项目（2026-08-25 JIAJIA 定）：赌馆博物馆不属真正的古建，
// 从演示库下架。定义与素材保留：它仍是第三项目泛化验证（T12）与 HABS 图纸转写链路的测试素材。
export const DEMO_PROJECTS: readonly DemoProjectDefinition[] = [GAODU_DEMO];
